sudo: required
dist: trusty

services:
  - postgres

language: ruby

branches:
  only:
    - master

env:
  global:
    - BUNDLE_GEMFILE="$TRAVIS_BUILD_DIR/Gemfile"
    - BUNDLE_PATH="$HOME/.bundle"
  matrix:
    - GEM=decidim_hospitalet-surveys DB=postgres

before_install:
  - gem update --system

# Skip the install step
install: true

cache:
  directories:
    - $HOME/.bundle
    - $TRAVIS_BUILD_DIR/.yarn-cache
    - $TRAVIS_BUILD_DIR/node_modules
    - $BUNDLE_PATH

script:
  - bundle install --jobs=3 --retry=3 --deployment --path="$HOME/.bundle"
  - bundle exec rake decidim:generate_test_app
  - cd $GEM && bundle exec rake

rvm:
  - 2.4.1

notifications:
    email: false

addons:
  postgresql: "9.4"
